# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Deter"
license = "MIT"
licenselink = "https://github.com/deter-project/docs/blob/master/LICENSE.md"
description = ""
homepage = "http://github.com/deter-project/docs"
tags = ["", ""]
features = ["", ""]
min_version = 0.13

[author]
  name = "ry"
  homepage = "deter-project.org"

