site_name: DeterLab Documentation (DEPRECATED)
site_description: User documentation for the DETERLab testbed
theme:
    name: readthedocs
    custom_dir: readthedocs_custom
site_dir: '_site'
extra_css: [css/extra.css]

pages:
- Welcome to the DETERLab Documentation: index.md
- Glossary: Glossary.md
- Quickstart: quickstart.md
- Opening Account: 
  - Research users: support/research.md
  - Class users: support/class.md
- Running Experiments:
  - Create a topology: core/topology.md
  - Create an experiment: core/create.md
  - Swap in an experiment: core/swapin.md
  - Use your nodes: core/interact.md
  - Swap out or terminate: core/swapout.md
  - User DOs and DON'Ts: core/user-guidelines.md
- Advanced Features:
  - Containers: containers/containers-quickstart.md
  - Nework Emulation: dsc/index.md
  - Risky Experiments: core/risky-experiment.md
  - Binary Analysis: https://binary.deterlab.net/docs 
  - Competitions: competitions/index.md
  - Orchestrator: orchestrator/index.md
  - Human user emulation: dash/index.md
- Sharing:
  - Sample Topologies: core/sample-topologies.md
  - Shared Materials: core/sharing.md
- Deterlab for Classes:
  - Education Materials Overview: education/index.md
  - Guidelines for Teachers: education/guidelines-for-teachers.md
  - Class Support: education/class-support.md
  - Course Setup: education/course-setup.md
  - Good Teaching Practices: education/good-teaching-practices.md
  - Connect With Other Teachers: education/connect-with-teachers.md
  - Guidelines for Students: education/guidelines-for-students.md
  - Public Materials: education/public-materials.md
- Reference:
  - DETERLab commands: core/deterlab-commands.md
  - NS commands: core/ns-commands.md
- Support:
  - Migration Instructions: support/migration.md
  - Getting Help: support/getting-help.md
  - FAQs: support/faqs.md
  - Usage Policy: support/usage-policy.md

markdown_extensions:
    - attr_list
    - toc:
        permalink: 
    - admonition:

copyright: Copyright &copy; 2018 <a href="https://www.deter-project.org/">DETER Project</a>.

#extra:
#  support: contact@partners.org
